In [16]:
import jax.numpy as jnp
import jax.scipy as jsp


In [3]:
ntheta = 15
x = jnp.zeros((15,3))
print(x.shape[0])

15


In [4]:
x = jnp.zeros(3)
print(x)
for i in range(len(x)):
    for j in range(10):
        x = x.at[i].add(j)
print(x)
print(x.shape[0])

[0. 0. 0.]
[45. 45. 45.]
3


In [5]:
from jax import grad, jit
import jax.numpy as jnp

def f(a,b):
    return 2*a**2 + b**3
def g(a,b):
    return a**2 + b**3

J = jit(lambda a,b : jnp.sum(jnp.array([grad(f,i)(a,b) for i in range(2)]))   ) 

In [6]:
print(f(1,1))
print(J(1.,1.,1.))
print(dJ(1.,1.,1.))

3


TypeError: <lambda>() takes 2 positional arguments but 3 were given

In [ ]:
J = jit(lambda a,b : jnp.sum( [f(a,b) ] )   ) 

In [ ]:
J_jax = jit(lambda a,b : 0)
for j in range(2):
    J = jit( lambda a,b : jnp.sum(jnp.array([jnp.minimum(jnp.linalg.norm(i-j),1)*a*b for i in range(2) ])))


In [ ]:
j=1
jnp.minimum(2.,1.)

In [ ]:
import numpy as np
np.min((1,2))

In [ ]:
J_jax = jit(lambda a,b,quad,i,j : jnp.minimum(jnp.linalg.norm(i-j),1)* f(a,b) + (1-jnp.minimum(jnp.linalg.norm(i-j),1))*g(a,quad)) 

def J(a,b,quad):
    E = 0.0
    for i in range(2):
        for j in range(2):
            E += J_jax(a,b,quad,i,j)
    return E

def dJ(a,b,quad):
    return 0.

In [ ]:
J(1,2,3)
for i in range(7):
    print(i)

In [2]:
def f_pure(a,b):
    return a + b**2 

class test():
    def __init__(self):
        self.c = 2.
        self.f = lambda a,b : f_pure(a,b)
        self.thisgrad = [lambda a,b : grad(f,argnums=i)(a,b) for i in range(2)]

    def J(self):
        return self.f
    
    def dJ(self):
        return self.thisgrad

In [7]:
from jax import grad, jit
Obj = test()
print(Obj.f)
print(Obj.J())
f = Obj.f
g = Obj.J()
print(g(1,2))
print(f(1,2))
gradient = Obj.dJ()
print(gradient)
derivatives = sum([gradient[i](1.,2.) for i in range(2)])
print(derivatives)

<function test.__init__.<locals>.<lambda> at 0x126ccff70>
<function test.__init__.<locals>.<lambda> at 0x126ccff70>
5
5
[<function test.__init__.<locals>.<listcomp>.<lambda> at 0x126ccfdc0>, <function test.__init__.<locals>.<listcomp>.<lambda> at 0x126ccf790>]
8.0


In [8]:
x = jnp.reshape(jnp.arange(0,12,1),(4,3))
print(x)
for i in range(4):
    print(jnp.dot(x[i,:],jnp.array([1,0,0])))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
3
6
9


In [ ]:
def J():
    array_gamma = jnp.array([coil.curve.gamma() for coil in self.coils])
    return self.E(array_gamma, ...)

def E(self, array_gamma, ...):
    resE = 0
    for ii, arrays_A in enumerate(array_gamma):
        for jj, arrays_B in enumerate(array_gamma):
            resE += self.J_jax(,ii,jj)

    return resE

def dJ(self):
    array_gamma = jnp.array([coil.curve.gamma() for coil in self.coils])
    dE_dG = jax.grad(self.E, argnums=0)(array_gamma, ..)
    dJ_1 = [self.coils[i].curve.dgamma_dcoeffs_vjp(dE_dG[i]) for i in range(len(self.coils))]
    dE_dI1 = jax.grad(self.E, argnums=1)(array_gamma, ..)
    dJ_2 = ..
    return np.concatenate((dJ_1, dJ_2))

In [7]:
dphi = 2*jnp.pi/75

y = jsp.integrate.trapezoid(x,dx=dphi)
print(y)
integrand = jnp.zeros(75)
double_int = 0.0
for i in range(75):
    x = jnp.linspace(0,2*i,75)
    integrand = integrand.at[i].set(jsp.integrate.trapezoid(x,dx=dphi))
print(integrand)
double_int = jsp.integrate.trapezoid(integrand,dx=dphi)
print(double_int)

7.539822
[  0.          6.1994095  12.398819   18.598228   24.797638   30.997051
  37.196457   43.39587    49.595276   55.794685   61.994102   68.193504
  74.392914   80.592316   86.79174    92.991135   99.19055   105.38997
 111.58937   117.78879   123.988205  130.1876    136.38701   142.58641
 148.78583   154.98523   161.18463   167.38406   173.58348   179.78287
 185.98227   192.1817    198.3811    204.58052   210.77994   216.97934
 223.17874   229.37814   235.57758   241.77696   247.97641   254.17581
 260.3752    266.57462   272.77402   278.9734    285.17282   291.37225
 297.57166   303.77106   309.97046   316.1699    322.36926   328.5687
 334.76813   340.96753   347.16696   353.36633   359.56573   365.76514
 371.96454   378.164     384.3634    390.5628    396.7622    402.9616
 409.16104   415.36047   421.55988   427.75928   433.95868   440.15808
 446.35748   452.5569    458.7563   ]
1422.009


In [32]:
ncoils = 4
indices1 = jnp.array(range(1,ncoils))
print(indices1) # 1,2,3
indices2 = jnp.array(range(0,ncoils-1))
indices2 = indices2.at[1].set(2) 
indices2 = indices2.at[2].set(3)
print(indices2) # 0,2,3 
indices3 = jnp.array(range(0,ncoils-1)) 
print(indices3) # 0,1,2

x = jnp.array(range(6))
print(x[indices1[0]])

[1 2 3]
[0 2 3]
[0 1 2]
1


In [ ]:
def f1(x1,xprime1, x2, xprime2): # mutual inductance
    return x1*xprime1 + x2*xprime2

def f2(x1,xprime1): # self inductance
    return x1*xprime1

def f(arrayx1, arrayx2, arrayxprime1, arrayxprime2):
    for i in range(arrayx1.shape[0]):
        

In [34]:
import numpy as np
np.logspace(-10, -4, 20)
x = []
y = [4,5,6]
x = np.concatenate((x,y),0)
print(x)
x = np.reshape(x,(-1,3))
print(x)

[4. 5. 6.]
[[4. 5. 6.]]


In [33]:
import numpy as np
import jax.scipy as jsp

x = np.array(np.random.rand(30,3))
print(np.linalg.norm(x,ord=2, axis=1))


[1.04312593 1.09208959 0.82369284 1.26413294 0.98356288 0.93024663
 0.41440292 1.20217434 1.05108253 1.31798708 0.63125317 0.34354968
 0.89400254 0.54937226 1.0160317  0.90086644 1.52738252 0.60807359
 1.06786748 0.5357713  1.10066658 1.01256084 0.46626761 0.30085882
 0.8800292  0.64699761 0.91441221 1.16048857 0.76166628 0.73840984]


In [16]:

import os, time, logging
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
import jax.numpy as jnp
import jax.scipy as jsp
from mayavi.mlab import *
from scipy.optimize import minimize
from simsopt.field import (InterpolatedField, SurfaceClassifier, LevelsetStoppingCriterion, BiotSavart, Current,
                            particles_to_vtk, compute_fieldlines, plot_poincare_data, coils_via_symmetries)
#from simsopt.field.force import ForceOpt, force_opt_pure, coil_force_pure
from simsopt.field.selffield import regularization_rect, B_regularized_pure, regularization_circ
from simsopt.geo import (SurfaceRZFourier, CurveLength, MeanSquaredCurvature, curves_to_vtk, create_equally_spaced_curves, plot)
from simsopt.geo.energy import CoilEnergy
from simsopt.objectives import Weight, SquaredFlux, QuadraticPenalty
from simsopt.util import in_github_actions, comm_world, proc0_print

ncoils = 4 # times 2 for stellsym * 2 for nfp 

# coils radii
R0 = 1.0
R1 = 0.5

# Number of Fourier modes describing each Cartesian component of each coil:
order = 3
                                                                            # LINEAR PENALTY WEIGHTS #
                                                                            # L: 1e-5, 1e-5
                                                                            # E: 1e-8, 1e-10
# Weights
LENGTH_WEIGHT = Weight(1e-6)    #1e-5 #1e-5
ENERGY_WEIGHT = Weight(1e-7)    #1e-8 #1e-10
MSC_THRESHOLD = 5
MSC_WEIGHT = Weight(0.0) #1e-6

# Number of iterations to perform:
MAXITER = 50 if in_github_actions else 400

# File for the desired boundary magnetic surface:
#TEST_DIR = (Path(__file__).parent / ".." / ".." / "tests" / "test_files").resolve()
filename = '/Users/salomonguinchard/Documents/GitHub/simsopt/tests/test_files/input.LandremanPaul2021_QA'

# Directory for output
OUT_DIR = "./output/"
os.makedirs(OUT_DIR, exist_ok=True)
 
# Make Poincaré plot
make_p2 = False

# Compute forces on coils
compute_forces = True

# run second optim with first one as initial guess
init_guess = False

# Penalize energy with a quadratic penalty
quad_pen = True
#######################################################


# Initialize the boundary magnetic surface:
nphi = 200   #32
ntheta = 512 #32
s = SurfaceRZFourier.from_vmec_input(filename, range="full torus", nphi=nphi, ntheta=ntheta)
nfp = s.nfp

# Create the initial coils:
base_curves = create_equally_spaced_curves(ncoils, s.nfp, stellsym=True, R0=R0, R1=R1, order=order)
base_currents = [Current(1e5) for i in range(ncoils)]
base_currents[0].fix_all() # Fix one current
coils = coils_via_symmetries(base_curves, base_currents, s.nfp, True)

# Field from these coils
bs = BiotSavart(coils)
bs.set_points(s.gamma().reshape((-1, 3)))

curves = [c.curve for c in coils]
curves_to_vtk(curves, OUT_DIR + "curves_init")
pointData = {"B_N": np.sum(bs.B().reshape((nphi, ntheta, 3)) * s.unitnormal(), axis=2)[:, :, None]}
s.to_vtk(OUT_DIR + "surf_init", extra_data=pointData)



In [ ]:
g0 = coils[0].curve.gamma()
nquad = coils[0].curve.quadpoints.shape[0]
gdash0 = coils[0].curve.gammadash()

print(np.linalg.norm(gdash0[:,:], axis=1))

print((gdash0*gdash0).shape)
print(np.sum(gdash0*gdash0, axis=1))

In [17]:

from scipy import constants
Biot_savart_prefactor = constants.mu_0 / (4 * np.pi)
def mutual_inductance_vec(gamma_1, gammadash_1, gamma_2, gammadash_2):
    """
    Mutual inductance of two coils carrying a current, optimized version.
    """
    r_c1 = gamma_1
    r_c2 = gamma_2
    rc_prime1 = gammadash_1 / jnp.pi
    rc_prime2 = gammadash_2 / jnp.pi
    dphi_1 = 2 * jnp.pi / r_c1.shape[0]
    dphi_2 = 2 * jnp.pi / r_c2.shape[0]
    
    # Compute distance matrix between points on the two different curves
    distance_matrix = jnp.sqrt(jnp.sum((r_c1[:, None, :] - r_c2[None, :, :]) ** 2, axis=-1))
    # Vectorized integrand calculation
    integrand_matrix = jnp.dot(rc_prime2, rc_prime1.T) / distance_matrix
    
    # Perform the double integral using vectorized operations
    integral = jnp.sum(integrand_matrix * dphi_1, axis=1)
    double_integral = jnp.sum(integral * dphi_2)
    
    return Biot_savart_prefactor* double_integral

g1 = coils[0].curve.gamma()
g2 = coils[1].curve.gamma()
gdash1 = coils[0].curve.gammadash()
gdash2 = coils[1].curve.gammadash()


In [102]:
print(jnp.dot(g1,g1.T)[1,:])

print((g1[1,:]-g1))
print(((g1[:,None,:]-g1[None,:,:])**2).shape)
print(jnp.sum((g1[:, None, :] - g1[None, :, :])[0,:,:] ** 2, axis=-1))
print((jnp.linalg.norm(g1 - g1)**2))

a=np.array([[0,4,3],[3,4,0]])
print(a.shape)
np.linalg.norm(a,axis=1)

[2.24270105 2.24026807 2.2233319  2.19222219 2.14754445 2.09016828
 2.02121045 1.94201314 1.85411783 1.75923532 1.65921237 1.55599583
 1.45159468 1.34804097 1.24735026 1.15148239 1.0623033  0.98154877
 0.91079059 0.85140599 0.80455083 0.77113708 0.75181511 0.746961
 0.75666922 0.78075082 0.81873708 0.86988864 0.93320989 1.00746835
 1.09121867 1.18283074 1.28052144 1.38238933 1.48645167 1.590683
 1.69305458 1.79157386 1.88432327 1.96949756 2.04543891 2.11066919
 2.16391879 2.20415125 2.23058349]
[[-4.77246746e-03 -9.49302802e-04 -6.95865505e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.42245117e-02  2.82943131e-03  6.82321274e-02]
 [ 3.76242038e-02  7.48391945e-03  1.33781771e-01]
 [ 6.97436278e-02  1.38728701e-02  1.95373082e-01]
 [ 1.09957616e-01  2.18719297e-02  2.51807254e-01]
 [ 1.57483448e-01  3.13254055e-02  3.01985862e-01]
 [ 2.11396088e-01  4.20492964e-02  3.44932236e-01]
 [ 2.70646189e-01  5.38348741e-02  3.79810473e-01]
 [ 3.34080513e-01  6.64527457e-02  4.0594

array([5., 5.])

In [25]:
f_int_max = np.zeros((2,ncoils))
forces = []

for i in range(ncoils):
    coils_ext = coils.copy()
    coils_ext.pop(i)
    bs = BiotSavart(coils_ext)
    bs.set_points(coils[i].curve.gamma()[1:-2])
    Bext = bs.B()
    B_self = B_regularized_pure(
        coils[i].curve.gamma()[1:-2], coils[i].curve.gammadash()[1:-2],coils[i].curve.gammadashdash()[1:-2], \
        2*jnp.pi*coils[i].curve.quadpoints[1:-2], coils[i].current.get_value(), regularization_rect(0.1,0.1))
    B_tot = B_self + Bext
    frenet_frame = coils[i].curve.frenet_frame()
    t = frenet_frame[0][:,:]
    force_pure = coil_force_pure(B_tot, coils[i].current.get_value(),t[1:-2])
    forces.append(force_pure)
    #f_int_max[0,i] = jnp.max(jnp.linalg.norm(force_pure, axis=1))
    f_int_max[0,i] = force_opt_pure(
        coils[i].curve.gamma()[1:-2], 
        coils[i].curve.gammadash()[1:-2], 
        coils[i].curve.gammadashdash()[1:-2], 
        coils[i].current.get_value(), 
        2*np.pi*coils[i].curve.quadpoints[1:-2],
        Bext, 
        regularization_rect(0.1,0.1)
        )
    print(force_pure.shape)
    print(coils[i].curve.quadpoints.shape[0])
    dphi = 2*np.pi/coils[i].curve.quadpoints.shape[0]
    f_int_max[1,i] = np.sqrt(jsp.integrate.trapezoid(np.linalg.norm(force_pure,ord=2, axis=1)**2, dx=dphi))
print(f_int_max.shape)
print("Forces on the obtained coils")
print(["coil " + f'{i+1}' for i in range(ncoils)])
print(f_int_max[0,:])
print(f_int_max[1,:])
array_forces = np.array(forces)
print(coils[0].current.get_value())

(42, 3)
45
(42, 3)
45
(2, 2)
Forces on the obtained coils
['coil 1', 'coil 2']
[15240.18038858 15240.18038858]
[27364.66363952 27364.66363952]
100000.0


In [2]:
import jax.numpy as jnp
print(np.linalg.norm(force_pure,ord=2, axis=1))
print(np.sqrt(jsp.integrate.trapezoid(np.linalg.norm(force_pure,ord=2, axis=1), dx=dphi)))
print(jnp.max(jnp.linalg.norm(force_pure, ord=2, axis=1)))
i=1
print(force_opt_pure(
        coils[i].curve.gamma(), 
        coils[i].curve.gammadash(), 
        coils[i].curve.gammadashdash(), 
        coils[i].current.get_value(), 
        2*np.pi*coils[i].curve.quadpoints,
        Bext, 
        regularization_rect(0.1,0.1)
        ))



NameError: name 'force_pure' is not defined

In [27]:
ncoils

2

In [10]:
import numpy as np
x = np.array([3,4,5])
print(x)
print(np.linalg.norm(x, ord=2)**2)

[3 4 5]
50.00000000000001


In [5]:
import numpy as np
import scipy.constants as constants

constants.mu_0/4/np.pi

1.0000000005443757e-07

In [33]:
from simsopt.configs.zoo import get_w7x_data, get_hsx_data, get_ncsx_data
import matplotlib.pyplot as plt
import numpy as np 
from simsopt.geo import SurfaceRZFourier, create_equally_spaced_curves

curves, curr, ax = get_w7x_data()
print(np.linalg.norm(curves[2].gammadash(), axis = 1))

ncoils = 4 # times 2 for stellsym * 2 for nfp 

# coils radii
R0 = 1.0
R1 = 0.5
order = 6

# Initialize the boundary magnetic surface:
nphi = 200   #32
ntheta = 512 #32
filename = '../../tests/test_files/input.W7-X_standard_configuration'
s = SurfaceRZFourier.from_vmec_input(filename, range="full torus", nphi=nphi, ntheta=ntheta)
nfp = s.nfp

# Create the initial coils:
base_curves = create_equally_spaced_curves(ncoils, s.nfp, stellsym=True, R0=R0, R1=R1, order=order)
print(print(np.linalg.norm(1/np.pi*base_curves[1].gammadash(), axis = 1)))

[0.99132043 0.99187252 0.99256723 0.99234105 0.99036272 0.993363
 0.99081741 0.99251463 0.99169971 0.99154191 0.99170104 0.99305976
 0.99112298 0.99161884 0.99233886 0.99224299 0.99140124 0.99152797
 0.99244594 0.99171144 0.99197714 0.99306401 0.99111863 0.99138044
 0.99389127 0.99025248 0.99303955 0.99203601 0.99240495 0.99145684
 0.99248146 0.99227217 0.99184708 0.99317962 0.99148996 0.99317797
 0.99173623 0.99209898 0.9928531  0.99215202 0.99261677 0.99251757
 0.99237283 0.99317683 0.99124754 0.99345669 0.99007221 0.99515689
 0.98887423 0.99549789 0.98907404 0.99632739 0.99001426 0.9955768
 0.99099805 0.99461937 0.99111625 0.99180751 0.99343044 0.99085961
 0.99282261 0.99204878 0.9915049  0.99277384 0.99155055 0.99307702
 0.99231203 0.99364623 0.99387515 0.99352751 0.99348656 0.99369973
 0.9937112  0.99286012 0.99397148 0.99261446 0.99424866 0.99032608
 0.99497691 0.99174813 0.99507037 0.99083737 0.99471232 0.99264653
 0.99300766 0.99268712 0.99254286 0.99118528 0.99272266 0.9927841